// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP2NKU9r74lo3M2isJdOpb4acAd6qpRwY',
    appId: '1:482008696520:web:b4a8c44d8e16628b4787fd',
    messagingSenderId: '482008696520',
    projectId: 'projetflutter-b0fdb',
    authDomain: 'projetflutter-b0fdb.firebaseapp.com',
    storageBucket: 'projetflutter-b0fdb.appspot.com',
    measurementId: 'G-07DPYZ8GG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkfz_3_jN4ONR7jWK2CUjLjl6HyZmPVC4',
    appId: '1:482008696520:android:8bb47a30f9f192cf4787fd',
    messagingSenderId: '482008696520',
    projectId: 'projetflutter-b0fdb',
    storageBucket: 'projetflutter-b0fdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAea_DJXWetThDSYOWZCa-EI3pqDtkz9F0',
    appId: '1:482008696520:ios:0a26db17c5b09f0e4787fd',
    messagingSenderId: '482008696520',
    projectId: 'projetflutter-b0fdb',
    storageBucket: 'projetflutter-b0fdb.appspot.com',
    iosClientId: '482008696520-4qhq65j9vcmspleu2avfo7h2q14qi8br.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFlutterEmsi',
  );
}
